"""auth

Revision ID: fab7ec08953e
Revises: 
Create Date: 2021-06-18 11:24:08.952977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab7ec08953e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_secret',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.String(length=127), nullable=True),
    sa.Column('app_sec_hash', sa.String(length=127), nullable=True),
    sa.Column('last_date', sa.String(length=20), nullable=True),
    sa.Column('date_token_num', sa.String(length=20), nullable=True),
    sa.Column('last_auth_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_secret')
    # ### end Alembic commands ###
